### ISSUE TITLE
warp账户提问

### ISSUE THREAD

**Issue by Extreme-Icer** [badafans/warp-reg#1]
关于这个生成的warp账户 有办法换掉license升级到warp+么？这个标准化注册的流量是多少？

**Comment by badafans** [comment]
标准化注册就是无限流量的，无需warp+

**Comment by Extreme-Icer** [comment]
> 标准化注册就是无限流量的，无需warp+

也就是目前这个warp足够了是吧

**Comment by badafans** [comment]
> 

足够用了，不要有心理障碍，放心用

**Comment by Extreme-Icer** [comment]
thx
