### ISSUE TITLE
windows virsion not working

### ISSUE THREAD

**Issue by Mahantor** [badafans/warp-reg#3]
i tested all version exe files but no one not working
windows 11 23h2

**Comment by badafans** [comment]
I can guide you through the steps:

1. Open a web browser and visit https://github.com/badafans/warp-reg/releases/download/v1.0/main-windows-amd64.exe.

2. Download the `main-windows-amd64.exe` file and save it to your computer.

3. Open the Windows Command Prompt (CMD).

4. In CMD, navigate to the directory containing the `main-windows-amd64.exe` file using the `cd` command, for example:

   ```bash
   cd path\to\directory
   ```

5. In CMD, run `main-windows-amd64.exe` by directly entering the filename and pressing Enter:

   ```bash
   main-windows-amd64.exe
   ```

6. If everything is correct, `main-windows-amd64.exe` should output configuration information to the CMD window.

Ensure that the file you download is trustworthy, as executing files downloaded from the internet may pose risks.
